language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t crackler/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true crackler/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app:  "docker"
  environment:  "Docker-env"
  bucket-name:  "elasticbeanstalk-us-east-2-498385989671"
  bucket-path:  "docker"
  on:
    branch: master
    access_key_id:  $AWS_ACCESS_KEY
    secret_access_key:  "$AWS_SECRET_KEY"